### ISSUE TITLE
Adding more text in the bottom label pushes the text offscreen from the top

### ISSUE THREAD

**Issue by silkynanda** [Xablu/Xablu.Walkthrough#24]
<img width="323" alt="screen shot 2017-11-08 at 10 54 10" src="https://user-images.githubusercontent.com/29792210/32542675-a1f750a4-c473-11e7-9b8c-8a063e574d59.png">

**Comment by MarcBruins** [comment]
Hi Silky. Can you provide a bit more information? Which device is this related to and which OS version? Also which theme/page?

**Comment by silkynanda** [comment]
Hi Marc, 

The issue is both on iPhone(ios 11 and ios 10.3) and Android (4.4,5, 6, 7 and 8) devices.
The theme is Theme<ForestPrimesPage, ForestPrimesContainer> and the issue is on all the pages.

**Comment by MarcBruins** [comment]
How do you want the theme to be? Obviously a phone screen is not that big and we cannot have everything. Three lines at the bottom and 1 line at the top maybe?

**Comment by silkynanda** [comment]
Is it possible to make the text resizable? As if you have longer translated text then it's no longer fit on the screen.

**Comment by MarcBruins** [comment]
At the bottom or at the top? What should happen if the top line is going to overlap the image?

**Comment by silkynanda** [comment]
The problem is you are having more text at the bottom then the text from the top goes off. But if you made the text in the bottom resizable then it might fix the issue

**Comment by MarcBruins** [comment]
Mm need to have a look on how the its implemented. I think the text is resizable at the bottom and that that is the issue. Because of the constraint it will push the rest of the views up and they get removed. Thinking there should be a fixed size and the TextView should not be resizable. Will have a look soon

**Comment by c-lamont** [comment]
@silkynanda We have implemented a fix for this issue, please see the attached image. The fix is being released now. On Android, when there is a lot of text in the description (which we advise against), the text become scrollable. 

Please remember also that all text is resizable using the `TextSize` property of the `TextControl`.

<img width="252" alt="screen shot 2018-01-08 at 11 44 50" src="https://user-images.githubusercontent.com/24552827/34728078-2b8b4508-f559-11e7-9798-1dbf3755d4d1.png">
